[project]
name = "content"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.20"
dependencies = [
    "accelerate>=0.30",
    "datasets==2.14.4",
    "dotenv>=0.9.9",
    "fsspec==2023.9.2",
    "google-genai",
    "graph-walker==1.0.6",
    "huggingface-hub>=0.36.2",
    "jupyter>=1.1.1",
    "networkx==3.1",
    "numpy==1.26.4",
    "openai==0.27.9",
    "peft==0.5.0",
    "pyarrow==14.0.2",
    "pybind11==2.11.1",
    "pydantic>=2",
    "sentencepiece==0.1.99",
    "setuptools>=82.0.1",
    "tiktoken>=0.13.0",
    "torch>=2.2",
    "tqdm>=4.67.3",
    "transformers>=4.40",
    "trl==0.7.1",
    "wandb==0.15.8",
]

[tool.uv.extra-build-dependencies]
graph-walker = ["pybind11"]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
]
